<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleName = 'Crystal - Fresh Responsive Magento Theme';
$moduleVersion = '1.0.0';
$moduleRevision = '84408d475a78d65bd334ddc0e7f4a7714d70ecfd';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/';